// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdrkqvngboPnzf8ZKqr2CizRcdSFm-ljg',
    appId: '1:338035775553:web:5e1f4aa42692f33e61cec0',
    messagingSenderId: '338035775553',
    projectId: 'nutttravel',
    authDomain: 'nutttravel.firebaseapp.com',
    databaseURL: 'https://nutttravel-default-rtdb.firebaseio.com',
    storageBucket: 'nutttravel.firebasestorage.app',
    measurementId: 'G-1Z3VJ75FBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGkIN-N0PFM1ppNDXR2Bsg4y6PHWAn7zM',
    appId: '1:338035775553:android:668b87561349e1b661cec0',
    messagingSenderId: '338035775553',
    projectId: 'nutttravel',
    databaseURL: 'https://nutttravel-default-rtdb.firebaseio.com',
    storageBucket: 'nutttravel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU8QoDzND-M-0q0saK4m-cm04s5kLI6vI',
    appId: '1:338035775553:ios:f0ef5e8a777d40d261cec0',
    messagingSenderId: '338035775553',
    projectId: 'nutttravel',
    databaseURL: 'https://nutttravel-default-rtdb.firebaseio.com',
    storageBucket: 'nutttravel.firebasestorage.app',
    iosClientId: '338035775553-tj5m4rs4horer165n9fjcr6vrsa94fst.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU8QoDzND-M-0q0saK4m-cm04s5kLI6vI',
    appId: '1:338035775553:ios:f0ef5e8a777d40d261cec0',
    messagingSenderId: '338035775553',
    projectId: 'nutttravel',
    databaseURL: 'https://nutttravel-default-rtdb.firebaseio.com',
    storageBucket: 'nutttravel.firebasestorage.app',
    iosClientId: '338035775553-tj5m4rs4horer165n9fjcr6vrsa94fst.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdrkqvngboPnzf8ZKqr2CizRcdSFm-ljg',
    appId: '1:338035775553:web:e6be46d97754b80361cec0',
    messagingSenderId: '338035775553',
    projectId: 'nutttravel',
    authDomain: 'nutttravel.firebaseapp.com',
    databaseURL: 'https://nutttravel-default-rtdb.firebaseio.com',
    storageBucket: 'nutttravel.firebasestorage.app',
    measurementId: 'G-V0F0LY8693',
  );

}