// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQrjBjKMNy2vZMxx6hU36HuprcKw_9QYM',
    appId: '1:182136814453:web:1ee3c572e487e8bedff13c',
    messagingSenderId: '182136814453',
    projectId: 'nutttravel-fffc6',
    authDomain: 'nutttravel-fffc6.firebaseapp.com',
    databaseURL: 'https://nutttravel-fffc6-default-rtdb.firebaseio.com',
    storageBucket: 'nutttravel-fffc6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCBT9dYy2iGCQE3YCiw7QHzZfZbWMkEvc',
    appId: '1:182136814453:android:4ef626144b64e21cdff13c',
    messagingSenderId: '182136814453',
    projectId: 'nutttravel-fffc6',
    databaseURL: 'https://nutttravel-fffc6-default-rtdb.firebaseio.com',
    storageBucket: 'nutttravel-fffc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1mgy3tQ-KzIwcgXS8zibixL3LW_YLXcU',
    appId: '1:182136814453:ios:e48626ae9ab05805dff13c',
    messagingSenderId: '182136814453',
    projectId: 'nutttravel-fffc6',
    databaseURL: 'https://nutttravel-fffc6-default-rtdb.firebaseio.com',
    storageBucket: 'nutttravel-fffc6.firebasestorage.app',
    iosBundleId: 'com.nutttravel.nutt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1mgy3tQ-KzIwcgXS8zibixL3LW_YLXcU',
    appId: '1:182136814453:ios:e48626ae9ab05805dff13c',
    messagingSenderId: '182136814453',
    projectId: 'nutttravel-fffc6',
    databaseURL: 'https://nutttravel-fffc6-default-rtdb.firebaseio.com',
    storageBucket: 'nutttravel-fffc6.firebasestorage.app',
    iosBundleId: 'com.nutttravel.nutt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQrjBjKMNy2vZMxx6hU36HuprcKw_9QYM',
    appId: '1:182136814453:web:9faa605622a9339edff13c',
    messagingSenderId: '182136814453',
    projectId: 'nutttravel-fffc6',
    authDomain: 'nutttravel-fffc6.firebaseapp.com',
    databaseURL: 'https://nutttravel-fffc6-default-rtdb.firebaseio.com',
    storageBucket: 'nutttravel-fffc6.firebasestorage.app',
  );
}
